apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detector-api
  labels:
    app: fraud-detector-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detector-api
  template:
    metadata:
      labels:
        app: fraud-detector-api
    spec:
      containers:
      - name: api
        image: 238788379449.dkr.ecr.ap-south-1.amazonaws.com/fraud-detector-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "180Mi"
          limits:
            cpu: "250m"
            memory: "300Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10