---
base : 
  project_name: "fraud-detector-mlops"
  random_state: 42
data:
  raw_data_path: "data/raw/raw_with_target.csv"
  processed_dir: "data/processed"
  train_path: "data/processed/train.parquet"
  test_path: "data/processed/test.parquet"
  temporal_split_column: "step"
  test_split_ratio: 0.20
  target_col: "isFraud"
  drop_cols:
    - "nameOrig"
    - "nameDest"
    - "isFlaggedFraud"
